public class NestedTryExample {
    public static void main(String[] args) {
        try {
            int[] array = {1, 2, 3};
            try {
                System.out.println(array[3]);
            } catch (ArrayIndexOutOfBoundsException e) {
                System.out.println("Inner catch: Array index out of bounds");
            }
        } catch (Exception e) {
            System.out.println("Outer catch: General exception");
        }
    }
}
